language: php
branches:
  only:
    - master
    - /^.*[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - '7.2'
script: phpunit --bootstrap src/autoload.php --test-suffix '-test.php,Test.php,.phpt'
  tests
notifications:
  email: false

before_deploy:
  - composer phar:install-tools
  - composer install --prefer-dist --no-dev --no-interaction
  - php box.phar build
deploy:
  - provider: releases
    skip_cleanup: true
    file: php-dependency-manager.phar
    api_key:
      secure: "NfCg9LYTxZSzJAntVNuSOCfNGh/yG9ruVhRJMT35VCLIOF+GBIsM7LCz35pK8WZE0vydBEqhtcdbALxSxDUcnQISzK9oATi604Ye/kHMEhB0HYhrcn0pFmzZfALLmxxO5kmiDJHrwCLW7BdKg+9sESLrLdJ3oPb7tTiLJj9u24ST/2USuJmdlNTV5PXlb7rmn4FfYX8Hbq13nY7nHZ5IjB8vC16u3HhSekxN0lRgdet9wJYeU84Czpu7DZ9ZmwYCMPVEhdSVoPLVMJCXT4vdWhKR3vSnTVxvXT3yyJF7zXSQ2lw826pTYuZdRisoDN74QdruDOUfxCEBl/NC/LbY0jb969G6vpxVC1Pxsr+Fs07Ikprsz/SFR3E2U7IbBWp5bgo7RUbh9YPtFvbMoa1b0RK6XOKy6Cflp1yEx5pXEYZwJYGqpUvkpKLe6tf2X5BMmYVfvSMmA3bF6SqTYfZwIHJCF6Q1+hIvXNi+nmDHkPEEmtj07UgOKPQ+YZu3GWDUqZKm4llL61SRP6VB/pPPHMJeb+dG0RMS0a5NSWB5SCxBz4xHgm1b13ZxuCh8yAhDm7NLURsfVCdn0vIUK/J1p856aj+UcasG/lKeNCRkWMkgIlUzxjmNqRlFnK0KLxmpmBT32sN/yEc07r+scHwJCibv0L7To44GtD7d/yIhf+Y="
    on:
      repo: bhoogter/php-dependency-manager
      tags: true

