language: php
branches:
  only:
    - master
    - /^.*[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - '7.2'
script: phpunit --bootstrap src/autoload.php --test-suffix '-test.php,Test.php,.phpt'
  tests
notifications:
  email: false

before_deploy:
  - composer phar:install-tools
  - composer install --prefer-dist --no-dev --no-interaction
  - php box.phar build
deploy:
  - provider: releases
    skip_cleanup: true
    file: php-dependency-manager.phar
    api_key:
      secure: "t/+8c71mTCH8mBJq2743fM+nMkAmmrhzEQDMoFLjA4H9tplym/ZATD4Z/ZB05CYbNpCjxLw9bEqIkS+4JrgBHrgv4DaZcHis4BmyJkAXUPhq9HGddjhOF6FvffJrrMfP78KrI8Egb096Zl6MYp7Gp/sxVS24qOVtlnflq29cNXQleHHV5lifwAjMPyuIg9MqlVYLhB+RHu9c8KNidhsln4ycxZULihUBqQKxjXZBMu9G26vPYUVj/51XMFJ02QxL+Il1E88Z6OURgQvKNcJ8nccRUFELIIdO2DzrkmRC/rDnqmQVWpJGwvma7JqG3c7Ieecm7eVJAZ8u3nOTNgHWqRbpv6diczFVRVPswu4hZhIUldzKI1g3j4aIQcBTvxA/XeFE8N2DWJDNdG65Le2LTkdsENfRhCXUao/mPwRpU0j/H+6xclZ/AgjwkjtHQViLvEpDvqYPC1Uvnx3LVJdOf5gPRfTVlltz9/I8I7PjoEOpX9CFNK0KTWgVMVT9bqs+f4YsNBQ58NQ1yB6T8EgIwkYRYilWhUVX0P9UcRzjayVM4gnDD68la1lAksfnlciUpFt2+wJt5MDzuOTu5LH47xWW0xfTRCCB0NvoTH2f1SZOwAcJnXZ5ea1qzKvadwhyHI1kSQD7xj8OHs1ryOQ="
    on:
      repo: bhoogter/php-dependency-manager
      tags: true

