language: php
branches:
  only:
    - master
    - /^.*[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - '7.2'
script: phpunit --bootstrap src/autoload.php --test-suffix '-test.php,Test.php,.phpt'
  tests
notifications:
  email: false

before_deploy:
  - composer phar:install-tools
  - composer install --prefer-dist --no-dev --no-interaction
  - php box.phar build
deploy:
  - provider: releases
    skip_cleanup: true
    file: php-dependency-manager.phar
    api_key:
      secure: "kQ53tqxlhs7v1MMgFx5gjM9Op6CH9++PdIsSUWNTh8xIabPj6+hQnQdY0tc0IKXkCsqkESFUGojvOQF9OiOYrOr42EJyYkN9tv+pY64C6sGYKPNOs6/UmlQaxYsL76xgpqaXBzhVWpxf3Z/hN3JTzCAzZ1G4bfqG4fLr/+64VypMUu1tjC7H2WZezL9rOI3frpmbE615cKDrTzSIpKjS+SVfcdPLZmab/vGoSdhHycB37faPs/Ga6lf/yYTg92lhZCzKcHwwLvduF3ggoTxujuoqNkxoch1rNCscam6waJ8MMOZ4LswtFHpRC87ll6KZEeXgGqc8sGx+i+neAfcyCFCjZxYnwEtr7LfYmz+lYEU2zucg2BJTaqsrg8fOCBqWdwNeJpQxXy8RSaR7KL8GyM9+3RVx5TJk4HXcJFxaGNTPZI6LwQjI8eFQMLPKhcnT/WKJCJZpzgmjwwhH0TZT5Kb6qoWJ9J64WC3CCrIpheHJ+ekAh0Q5hH2RPcMtU+DxJXrt0Nqc5BpLuxeyG+MItWuPxQcVzm/El/DQ1eTE1p2wIN44L3ffZxywQr2ekzB15qQCH2nUjZVr71lxqFasVseEW38yZKR/G5JLoUMnHBWPr8UyGpwQ6Z2Y6BXFtmqygDShompvE1Zi40tjeap9LFoJJB69C09AHbbu4qP2NUQ="
    on:
      repo: bhoogter/php-dependency-manager
      tags: true

