#!/bin/bash
set -e

cd $(dirname $0)

BOX=''
if [[ -f "box.phar" ]]; then BOX=box.phar; fi
if [[ -f "../box.phar" ]]; then BOX=../box.phar; fi
if [[ "$BOX" == "" ]]; then 
	echo 'Installing the boxer...'
	composer phar:install-tools
	composer install --prefer-dist --no-dev --no-interaction
	$($0)
	exit 0
fi

echo "Packaging project..."
php ${BOX} build
echo "Complete."
